apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ovs-br1-bond1-workers
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  desiredState:
    interfaces:
    # ---- bond1 (active-backup) ----
    - name: bond2
      description: Active-backup bond for OVN localnet
      type: bond
      state: up
      ipv4:
        enabled: false
      ipv6:
        enabled: false
      link-aggregation:
        mode: active-backup
        options:
          miimon: "100"
        port:
        - ens37
        - ens38

    # ---- OVS bridge br0 ----
    - name: br1
      description: OVS bridge for OVN localnet using bond1
      type: ovs-bridge
      state: up
      bridge:
        options:
          stp: true
        port:
        - name: bond2

    # ---- OVN localnet bridge mapping ----
    ovn:
      bridge-mappings:
      - localnet: br1-network
        bridge: br1
        state: present
